# Generated by Django 5.2.9 on 2025-12-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='csv_text',
            field=models.TextField(blank=True),
        ),
    ]
