# Generated by Django 5.2.9 on 2025-12-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importjob_csv_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='s3_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
