# Generated by Django 5.2.9 on 2025-12-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_importjob_s3_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importjob',
            name='file',
        ),
    ]
